title: Default
items:
  home:
    title: 'HOME'
    url: 'home'
    order: 1
  about:
    title: 'WTF !'
    url: 'wtf'
    order: 2
  sources:
    title: 'SOURCES'
    url: 'sources'
    order: 3
