title: FriendZone
description: 'Welcome to the FriendZone'
keywords: 'flextype, php, cms, flat-file cms, flat cms, flatfile cms, html'
robots: 'index, follow'
author:
  name: Lionel
  email: lionel.lft@me.com
timezone: Europe/Brussels
charset: UTF-8
date_format: 'F d Y H:i:s'
theme: default
locale: fr
entries:
  main: home
  media:
    upload_images_quality: 70
    accept_file_types: 'gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg'
    upload_images_width: 1600
    upload_images_height: 0
  error404:
    title: 'Error 404'
    description: 'Seems that you''re even deeper in the FriendZone now...'
    content: 'We''re sorry but the page you are looking for doesn''t appear to exist!'
    template: default
errors:
  display: true
cache:
  enabled: true
  prefix: flextype
  driver: auto
  lifetime: 604800
  memcache:
    server: localhost
    port: '11211'
  memcached:
    server: localhost
    port: '11211'
  redis:
    socket: ''
    password: ''
    server: localhost
    port: '6379'
  sqlite3:
    database: flextype
    table: flextype
admin_panel:
  theme: dark
